title: Jinchao Tao's Homepage
page-top-title: Jinchao Tao
top-section-bg-text: Computer Science
home-subtitle: Jinchao Tao&ensp;|&ensp;陶锦超
copyright-text: '&copy; Jinchao Tao 2024-2025. All Rights Reserved.'
